### ISSUE TITLE
Success report: Noname 2.4" ILI9341 display

### ISSUE THREAD

**Issue by johndoe31415** [juj/fbcp-ili9341#111]
Hi there, this isn't a bug -- it's a success report. Not sure if you're interested in those?

I successfully got a noname display ("Surenoo Technologies" was the seller on Aliexpress), 2.4" with ILI9341 to work using fbcp-ili9341. The seller referenced the [documentation here](http://www.lcdwiki.com/2.4inch_RPi_Display). Built it using:

```
cmake -DSPI_BUS_CLOCK_DIVISOR=6 -DILI9341=ON -DGPIO_TFT_DATA_CONTROL=22 -DGPIO_TFT_RESET_PIN=27 -DSTATISTICS=0 ..
```

Extremely straightforward, ran immediately. Very smooth installation, extremely well-documented project, thank you so much. I'm so happy that I have a display running using code I trust instead of some arbitrary binblob :-)

Take care, Johannes

![DSCF2135](https://user-images.githubusercontent.com/5919339/65589546-85cf9c00-df89-11e9-8e0e-10a1e04506bd.jpg)
![DSCF2141](https://user-images.githubusercontent.com/5919339/65589547-85cf9c00-df89-11e9-8484-bb9ea208a427.jpg)
![DSCF2143](https://user-images.githubusercontent.com/5919339/65589548-85cf9c00-df89-11e9-9d5e-bc195dd06bec.jpg)

**Comment by juj** [comment]
Very nice, thanks for the writeup. Makes me happy to read that the project is useful to you!

**Comment by juj** [comment]
Also really cool project with BeatSaber, that game is awesome :)
