### ISSUE TITLE
Keynes Screen ST7735 - Screen Size detected wrong

### ISSUE THREAD

**Issue by ReadieS** [juj/fbcp-ili9341#112]
I bought a screen from ebay [linked here](https://www.ebay.co.uk/itm/Keyes-128x160-Colour-TFT-LCD-Module-MD-333-Micro-SD-SPI-Arduino-Pi-Flux-Workshop/113204906182?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649)

I can get the screen to display but it doesn't take up the whole screen and displays portrait rather than landscape.

My current Cmake script is:
`cmake -DST7735S=ON -DGPIO_TFT_DATA_CONTROL=24 -DGPIO_TFT_RESET_PIN=25 -DSPI_BUS_CLOCK_DIVISOR=6 ..`

Upon running fbcp-ili9341 the following script is displayed:
```
pi@raspberrypi:~ $ sudo /home/pi/fbcp-ili9341/build/fbcp-ili9341 &
[1] 562
pi@raspberrypi:~ $ bcm_host_get_peripheral_address: 0x20000000, bcm_host_get_peripheral_size: 33554432, bcm_host_get_sdram_address: 0x40000000
BCM core speed: current: 400000000hz, max turbo: 400000000hz. SPI CDIV: 6, SPI max frequency: 66666667hz
Allocated DMA channel 7
Allocated DMA channel 1
Enabling DMA channels Tx:7 and Rx:1
DMA hardware register file is at ptr: 0xb4aff000, using DMA TX channel: 7 and DMA RX channel: 1
DMA hardware TX channel register file is at ptr: 0xb4aff700, DMA RX channel register file is at ptr: 0xb4aff100
Resetting DMA channels for use
DMA all set up
Initializing display
Resetting display at reset GPIO pin 25
InitSPI done
Relevant source display area size with overscan cropped away: 720x480.
Source GPU display is 720x480. Output SPI display is 130x129 with a drawable area of 128x128. Applying scaling factor horiz=0.18x & vert=0.18x, xOffset: 2, yOffset: 22, scaledWidth: 128, scaledHeight: 85
Creating dispmanX resource of size 128x85 (aspect ratio=1.505882).
GPU grab rectangle is offset x=0,y=0, size w=128xh=85, aspect ratio=1.505882
All initialized, now running main loop...
^C
```
As far as I can tell this says it detects my screen as 130 x 129 where it should be 160 x 128?

My Current `/boot/config.txt` file is the following:
```
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on
start_x=1
gpu_mem=128

#hdmi_group=2
#hdmi_mode=87
hdmi_cvt=160 128 1 60 0 0 0
#display_rotate=1
```
Adding the hdmi_cvt line has actually made things worse the text is now split and going diagonally across the screen.

Does anyone more experienced have and help they could offer me?

This image shows the area of the screen that is always used. the hdmi_cvt line is enables so text is fractured diagonally?
![2019-09-25 12 45 49](https://user-images.githubusercontent.com/29860881/65598913-6e49e080-df94-11e9-84d8-a333c9b35bdf.jpg)

This is the details from the back of the screen
![2019-09-25 12 46 27](https://user-images.githubusercontent.com/29860881/65598914-6e49e080-df94-11e9-899b-62a85ab79264.jpg)

Thanks,

**Comment by juj** [comment]
You probably need to manually modify madctl register and screen size in https://github.com/juj/fbcp-ili9341/blob/master/st7735r.cpp#L56 and the corresponding st3375r.h file. The only st7735s display I have tested with was a 128x128 display with internal memory area the size of 130x129 pixels. The resolution cannot actually be detected from the connected display (driver protocol does not have discovery functionality), so the driver just has to “spontaneously know” what is there on the other end, hence the need to manually tune these, in case there are different sizes that use the same controller.
