### ISSUE TITLE
Support for PI1 A+

### ISSUE THREAD

**Issue by elKevinPillo** [juj/fbcp-ili9341#113]
Hi, first of all, great work thank you so much!

Secondly, I wanted to let you know that I tried this on a RPI 1 A+ (512 RAM model) and it worked great (generic 2.8 tft display). Cheers!

**Comment by juj** [comment]
That’s great to hear! Pi 1 is pretty constrained in performance, though hopefully not too far away from Pi Zero. If the driver is eating too big time slices from the system, lowering the target frame rate in config.h may help cut the cpu free.
