### ISSUE TITLE
ILI9486: temporary white screen after 1 minute of inactivity

### ISSUE THREAD

**Issue by damienchallet** [juj/fbcp-ili9341#117]
I have one of these 3.5'' Waveshare clones. Using the   -DWAVESHARE35B_ILI9486=ON everything works (with an RPi2B). The only snag is that if nothing happens on the screen after exactly 1 minute, the screens turns white. When there is a screen update, the screen is properly redrawn and can be used as if nothing had happened.

**Comment by juj** [comment]
Try commenting out the display inactivity config line in config.h if that might have an effect?

**Comment by damienchallet** [comment]
Thanks. That worked! I understand that turning the display off is still not
understood (and I do not need it).
