### ISSUE TITLE
90-degree rotation?

### ISSUE THREAD

**Issue by retrohedron** [juj/fbcp-ili9341#119]
Thanks for all the work you put into this driver! I, like many others, was disappointed the first time I witnessed the performance of these displays. I'm happy to report that thanks to this driver I have one working beautifully-- an HX8357D on a Raspberry 2B 1.1. (Solid on clock divisor 14, but had it looking good at 10).

I'm sorry if I missed it, but it didn't look like there was any option for a 90-degree display rotation. I've been tinkering with it myself but to no avail. Any chance of getting this to work?

Edit: just saw the thread here https://github.com/juj/fbcp-ili9341/issues/56, so I'll give that a shot!

**Comment by juj** [comment]
Sorry, missed this thread. Hopefully #56 worked out ok. Closing out old issues, so feel free to reopen if there was an unresolved issue.
