### ISSUE TITLE
problem with st7789 

### ISSUE THREAD

**Issue by xinanhuang** [juj/fbcp-ili9341#121]
Hi! I got one the cheap 240x240 1.3 inch display that has the DC lines and try to emulate the pin connection to that of the waveshare display hat. so far I haven't gotten any success with both pi zero and pi 3b+. I'm on raspbian buster btw. The screen stays blank and the backlight is on the entire time. Nothing changes when I run the compiled program. I've tried both options for st7789 and st7789vw. Would really appreciate it if someone can point me towards the right direction, Thanks!

these are the cmake options ive tried so far:
cmake -DST7789=ON -DGPIO_TFT_DATA_CONTROL=25 -DGPIO_TFT_BACKLIGHT=24 -DGPIO_TFT_RESET_PIN=27 -DSPI_BUS_CLOCK_DIVISOR=30 ..

cmake -DST7789VW=ON -DGPIO_TFT_DATA_CONTROL=25 -DGPIO_TFT_BACKLIGHT=24 -DGPIO_TFT_RESET_PIN=27 -DSPI_BUS_CLOCK_DIVISOR=30 ..

cmake -DST7789VW=ON -DGPIO_TFT_DATA_CONTROL=25 -DGPIO_TFT_BACKLIGHT=24 -DGPIO_TFT_RESET_PIN=27 -DSPI_BUS_CLOCK_DIVISOR=30 -DUSE_DMA_TRANSFERS=OFF
  ..

EDIT: I've confirmed the display works by trying out with an ESP32

**Comment by albflo** [comment]
Did you find a solution for your issue?

**Comment by ClimbSnail** [comment]
You can see if it is this screen https://www.bilibili.com/video/BV1kC4y1a7fS/. I will lead out the CS pin of the screen and connect it to SPI_CE0 to work.

**Comment by juj** [comment]
Closing out old issues. Feel free to reopen if still struggling with a problem.
