### ISSUE TITLE
Display doesn't show the image, flashing pixels for one second

### ISSUE THREAD

**Issue by russinet** [juj/fbcp-ili9341#124]
In short, here is the video:  https://youtu.be/Gyj_CsjY0OI. Please help me identify the problem. It's definitely not GPIO pins. I am using waveshare 240x240 display. Can you please list all (or at least some) things that can cause this? I am quite new to this field and am not sure where to start.

**Comment by juj** [comment]
Sorry, missed this issue. I am unfortunately unable to view the YouTube video. Hopefully you were able to make it work.

If not, trying out the original Waveshare driver as a first stab is recommended. That will help debug that the physical connection works out ok. Given that this is an old issue, I'll close it, but feel free to reopen if you are still actively working on this.
