### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by C112358** [juj/fbcp-ili9341#135]
Hi,
I got this up and running, but no longer need fbcp-ili9341 on my Retropie install. How can I remove it from my microSD card? 
Thank you!

**Comment by juj** [comment]
To uninstall, you can follow the reverse steps of what you used to add fbcp-ili9341 to your SD card.

E.g. if you edited `/etc/rc.local`, re-edit it and remove the added lines. Same for `/boot/config.txt`. To get rid of the `git clone`d repository, you can just remove the directory: `rm -r /home/pi/fbpc-ili9341`.
