### ISSUE TITLE
Rpi4

### ISSUE THREAD

**Issue by ElKoziRRo** [juj/fbcp-ili9341#140]
Trying to build on rpi4 and getting message:
--Board revision: c03112
CMAKE WARNING
The board revision of this hardware is not known. Please add detection to this board in CMakeList.txt

Can we fix this?

**Comment by juj** [comment]
The warning will go away by editing https://github.com/juj/fbcp-ili9341/blob/master/CMakeLists.txt#L36 . A number of existing Pi4 revisions are already listed there.

**Comment by ElKoziRRo** [comment]
Thanks adding my rev at this place just fixed it
