### ISSUE TITLE
EmulationStation logo is green instead of blue

### ISSUE THREAD

**Issue by holadivinus** [juj/fbcp-ili9341#145]
im sure this is a super easy fix, like add one line to the cmake build options, but what should i add?

**Comment by holadivinus** [comment]
my current build cmd is 
`cmake -DWAVESHARE35B_ILI9486=ON -DUSE_DMA_TRANSFERS=OFF -DSPI_BUS_CLOCK_DIVISOR=30 -DDISPLAY_INVERT_COLORS=ON -DDISPLAY_SWAP_BGR=ON ..`

**Comment by juj** [comment]
The relevant flag would be -DDISPLAY_SWAP_BGR=ON or -DDISPLAY_SWAP_BGR=OFF. If that does not help, check out #130, if that might be the issue.

**Comment by holadivinus** [comment]
I tested both differences, but the colors are still off. i will look at issue 130

**Comment by juj** [comment]
Closing out old issues.
