### ISSUE TITLE
Set up freeze on raspberry pi

### ISSUE THREAD

**Issue by dh928** [juj/fbcp-ili9341#157]
it gets stuck at running main loop now(maybe it works but takes a long time?). I am trying to set up the driver on my raspberry pi4.
![bug](https://user-images.githubusercontent.com/52692636/89923144-247ae080-dbce-11ea-8c0a-11ad72e98b89.jpg)
what should I do?

**Comment by juj** [comment]
At that stage the driver is running normally. If nothing is showing up on the screen, then it means that something is going wrong with the messaging to the display. Check through the troubleshooting checklist on the main readme page for ideas what to try.

**Comment by dh928** [comment]
> At that stage the driver is running normally. If nothing is showing up on the screen, then it means that something is going wrong with the messaging to the display. Check through the troubleshooting checklist on the main readme page for ideas what to try.

Thank you! I change bus clock I visor to 30 and it worked!
