### ISSUE TITLE
Support for Pi2

### ISSUE THREAD

**Issue by jacktime192** [juj/fbcp-ili9341#17]
Super nice work! 
I just tried your code on a Raspberry Pi 2 and it worked out of the box (Waveshare 3.5B).
However, the lowest/best CDIV value I could achieve was 12, everything lower ended in a non-usable picture ;) But with this value I already got a smooth result.
Btw for me N64 games on Retropie only work with disabled DMA, just to let you know (at least the ones I tried).

**Comment by juj** [comment]
Thanks, nice to hear!

Not sure what the DMA thing is about. Perhaps N64 emulators utilize some specific DMA channels on their own, you could try changing the used DMA channels to see if that might help. CDIV=12 on WaveShare 3.5B sounds excellent performance, that's better than what I was able to do - my WaveShare 3.5B display maxes out at CDIV=14.
