### ISSUE TITLE
SPI stops talking to ST7789

### ISSUE THREAD

**Issue by krzysztofkuczek** [juj/fbcp-ili9341#170]
Hi,
I'm trying to compile it for little 240x240 ST7789 display (1,3inch from https://pl.aliexpress.com/item/32950879136.html) and it does not work.
Trying to investigate what's is going on i found out that after less then 1s from reset SPI stops sending any data.
What do i wrong?
<img width="1795" alt="st7789" src="https://user-images.githubusercontent.com/1246883/94846477-7b0fd880-0421-11eb-979d-430ba2cc0e90.png">

Kris
PS
I was trying with waveshare 128x128 display ant it works fine, so rpi hardware (rpi 3 v 1.2) seems to be ok.

**Comment by juj** [comment]
That is hard to say.. certainly nothing is moving there.

Does the same hang happen with both DMA enabled and disabled?

**Comment by juj** [comment]
Closing out old issues.
