### ISSUE TITLE
Frame buffer 90 degree orientation issue on ST7789v circular display [leaves a gap in the bottom]

### ISSUE THREAD

**Issue by dattasaurabh82** [juj/fbcp-ili9341#176]
Hey @juj.

**SYS**:           rpi4
**TFT**:          1.3" ST7789V 240x240 4 wire SPI circular display
**Side Note**: Another HDMI display is connected on the HMDI-1 (2nd HDMI) acting as a 2nd display Works fine. As in mentioned [issue 175](https://github.com/juj/fbcp-ili9341/issues/175)

Now I'm trying to actually make the frame buffer go properly portrait: 
Here's what I mean and is facing another challenge. ☹️
### Trial 0
![image](https://user-images.githubusercontent.com/4619862/98797833-0da38e80-2448-11eb-8fcc-924e5b6d5a0b.png)

### Trial 1
- In `config.h`, comment out **line 162**: `// #define DISPLAY_OUTPUT_LANDSCAPE`
- In `config.h`, un-comment **line 158**: `#define DISPLAY_ROTATE_180_DEGREES`
- In `st7735r.cpp`, editing **line 95**: `SPI_TRANSFER(0x37, 0, 40); // column value set to 40 for my display`

And then after compiling I get it mirrored and also not completely down: 

![image](https://user-images.githubusercontent.com/4619862/98799465-1c8b4080-244a-11eb-9ac5-a3872f7a41c2.png)

### Trial 2
-  In `config.h`, un comment **line 162**, `#define DISPLAY_OUTPUT_LANDSCAPE`
-  In `st7735r.cpp`, following your comments on the the [issue 29](https://github.com/juj/fbcp-ili9341/issues/29), I added, 
```
madctl ^= MADCTL_ROW_COLUMN_EXCHANGE;
madctl ^= MADCTL_COLUMN_ADDRESS_ORDER_SWAP;
```
Just before **line 69**, `SPI_TRANSFER(0x36/*MADCTL: Memory Access Control*/, madctl);`

- In `st7735r.cpp`, editing **line 95**: `SPI_TRANSFER(0x37, 0, 40); // column value set to 40 for my display`

And then I could get the display properly oriented in portrait (my intended portrait mode) 

Note: If we keep in `/boot/config.txt`, `hdmi_cvt=240 240 100 1 0 0 0` , the value `100 `for freq of `100 Hz`, then, upon reboot, the SPI display and the attached HDMI-1 display get **mirrored**. Upon playing with different values, the smallest value here would be `80`, I found. So something like  `hdmi_cvt=240 240 80 1 0 0 0` can be used in there to keep the 2nd HDMI display separate from the SPI display.

![image](https://user-images.githubusercontent.com/4619862/98805985-6f1d2a80-2453-11eb-97c8-93b7b7771ffb.png)

This is 90% of what I intended 😅

_Now my question is how do I rotate it 180 degrees in this portrait mode properly and are my steps correct?_

Note: Keeping the current setting from above mentioned **Trial 2**, I have tried editing the `config.h`, naively uncommenting l**ine 158** `#define DISPLAY_ROTATE_180_DEGREES `. 
It doesn't work! 😞 
As it rotates the display surely and there is no mirroring problem but also the frame buffer moves up a bit leaving a gap below. 

How can it be fixed?

**Comment by juj** [comment]
Rotation is handled by the MADCTL register. This line should be doing the trick: https://github.com/juj/fbcp-ili9341/blob/662e8db76ba16d86cf6fd09d85240adc19e62735/st7735r.cpp#L65-L69

I belive the gap may be caused by this line:
https://github.com/juj/fbcp-ili9341/blob/662e8db76ba16d86cf6fd09d85240adc19e62735/st7735r.cpp#L95

Try commenting that out, or forcing that to be unconditionally present? I am not quite sure about that directive, because different people have reported it to behave differently for them, in a few conflicting ways. Never really got to the bottom of it.
