### ISSUE TITLE
MHS-3.5inch RPi Display working perfectly.

### ISSUE THREAD

**Issue by Jpe230** [juj/fbcp-ili9341#191]
I'm writing this in case anyone happens to buy this display or is interested in a fast 3.5 SPI display

I was looking for a faster display than my current Waveshare 3.5inch RPi LCD, using it for gaming is totally unacceptable, even with fbcp-ili9341, the screen tears horrible and I couldn't get acceptable framerates, that's why I search for a faster display for my Pi Zero.

 I found [this](http://www.lcdwiki.com/MHS-3.5inch_RPi_Display) in Amazon and decided to buy it because of the theoretical SPI bus speed (125 MHZ) only to found out that the drivers are totally trash, so again no gaming with the "stock" drivers.

Decided to give it a try using fbcp-ili9341 and the results dropped my jaw, gameplay is buttery smooth and with minimal tearing.

According to the [wiki](http://www.lcdwiki.com/MHS-3.5inch_RPi_Display) this display uses the same pin definition and lcd driver as the Waveshare so to generate the makefile for fbcp-ili9341 I used:

`cmake -DWAVESHARE35B_ILI9486=ON -DSPI_BUS_CLOCK_DIVISOR=4`

It worked amazing, even on a Pi Zero. 

This is the display (from the back)
![IMG_6567-exif-remove](https://user-images.githubusercontent.com/6202305/107867815-9f55da00-6e43-11eb-94ef-d25c01163792.jpeg)

The big chip is what I assume is the LCD Driver but for some reason the IC is completely unmarked.
![IMG_6564-exif-remove](https://user-images.githubusercontent.com/6202305/107867813-9cf38000-6e43-11eb-9e85-60253954a398.jpeg)

The other chip is the XT2046.
![IMG_6566-exif-remove](https://user-images.githubusercontent.com/6202305/107867814-9ebd4380-6e43-11eb-87d6-46618776f094.jpeg)

And here it is playing SMB, the gameplay is buttery smooth and I can't notice lag nor tearing. 
![IMG_6568-exif-remove](https://user-images.githubusercontent.com/6202305/107867816-9fee7080-6e43-11eb-83e8-ae87a46a640e.jpeg)

**Comment by juj** [comment]
Great to see that these 125MHz displays are becoming more common.

Pi Zero can certainly push the bandwidth, but it does cause a bit high CPU stress on DispmanX, so more complex applications can stutter, e.g. SNES emulated games iirc.

**Comment by Matthew1471** [comment]
Same but I had to use

`cmake -DWAVESHARE35B_ILI9486=ON -DSPI_BUS_CLOCK_DIVISOR=4 -DUSE_DMA_TRANSFERS=OFF ..`

On a Raspberry Pi 3B
