### ISSUE TITLE
Pirate Audio 1.3 Support? (ST7789 driver)

### ISSUE THREAD

**Issue by antiero** [juj/fbcp-ili9341#199]
Hey all, has anyone had success getting the driver to work with this?

https://shop.pimoroni.com/products/pirate-audio-line-out

**Comment by ricmatsui** [comment]
@antiero I created #203 with some changes needed to be able to use it attached directly as a pHAT, otherwise you would need to connect the hat's LCD Data/Command to another GPIO pin to resolve the conflict with SPI MISO and LCD SPI CS to CS0 on the Pi since the driver expects the display with CS0.
