### ISSUE TITLE
How do I rotate 90 degree?

### ISSUE THREAD

**Issue by superjovie** [juj/fbcp-ili9341#212]
St7789 240x240 module

**Comment by juj** [comment]
Updated the documentation to directly talk about 90 degrees rotation, see above commit.

**Comment by superjovie** [comment]
I have done what you updated but the image seems in a mirror mode.can you tell me why?

**Comment by juj** [comment]
Hmm, if you get mirroring, then try adding a line

```c
madctl ^= MADCTL_ROW_ADDRESS_ORDER_SWAP;
```
or 
```c
madctl ^= MADCTL_COLUMN_ADDRESS_ORDER_SWAP;
```

after this line:

https://github.com/juj/fbcp-ili9341/blob/1db808e883597a29d069efbbdbd3e72bee852932/st7735r.cpp#L59
