### ISSUE TITLE
135x240 display from aliexpress. Will it work?

### ISSUE THREAD

**Issue by Arsen474** [juj/fbcp-ili9341#214]
Salut everyone. I am beginner in all this but i wanna make mini pc that will be base on raspberry pi zero. Display has a ST7789V driver and interface 4W-SPI. Can i use this library with [this display](https://aliexpress.ru/item/4000661571044.html?spm=a2g0o.cart.0.0.2a3c3c00rCRUZt&mp=1&_ga=2.196004907.662443575.1622168881-1684680615.1605642503&_gac=1.217102948.1622170208.Cj0KCQjwhr2FBhDbARIsACjwLo06qKqt0Rmlekj8Gz67ajZhM5bl9_muJ84k42_8VsrAcJ9AFhel8EcaApGVEALw_wcB&sku_id=10000005519217295)? 

Thanks for all answers :)

**Comment by juj** [comment]
ST7789V should work, but the driver backend has not been developed/tested for that pixel resolution specifically. You will need to modify the files to adjust for that pixel display size, and maybe adjust some display boot config parameters.
