### ISSUE TITLE
keyboard event

### ISSUE THREAD

**Issue by am7619** [juj/fbcp-ili9341#23]
this driver is a great piece of work, thanks!!!
however, my keyboard was on another event (/dev/input) resulting in an error and i am planning to use no keyboard at all. is it possible to exclude the keyboard events e.g. as a compiler option?

**Comment by juj** [comment]
Are you using the `BACKLIGHT_CONTROL` option? Currently keyboard control is hooked onto that option. Added `config.h` item `#define BACKLIGHT_CONTROL_FROM_KEYBOARD` that you can comment out to disable reading the keyboard altogether, even if using backlight control. That should do what you are looking for?

**Comment by am7619** [comment]
indeed, i activated `BACKLIGHT_CONTROL` without fully understanding it. my fault. thank you very much for your help!

**Comment by juj** [comment]
Perfect, great to hear it works!
