### ISSUE TITLE
Adafruit 2" TFT ST7789 shifting image to the right

### ISSUE THREAD

**Issue by voyager123456789** [juj/fbcp-ili9341#251]
I have the Adafruit 2" TFT ST7789 and have got it working, however there is black bar about a quarter of the way across the screen that starts the image that wraps around to the other side of the screen. However, it seems like this black bar should contain information as (what is supposed to be) the right most edge of the screen is cut off. I have tried messing around with config.txt and over scan parameters but all it seems to do is change the size of the black bar. I can't shift the image to the correct framing and the black bar is as small as it seems to go. Any ideas?
![IMG_1706](https://user-images.githubusercontent.com/15106715/145622519-2b4f6239-8ad6-4c99-8d3e-7a40a8695a21.JPEG)

**Comment by XEROxMEXICANO** [comment]
Hello I'm also having this issue. 
Did you ever find a solution?
