### ISSUE TITLE
General questions and suggestions

### ISSUE THREAD

**Issue by Kjos** [juj/fbcp-ili9341#42]
Hi,
Love this project, really innovative way to deal with the hardware limitations. Great work.
I have some suggestions:
- Maybe post the maximum refresh rate achieved with each display, or does it top at 120hz for all? Anyway, it's pretty cool that it achieves 120hz and deserves a line in the readme. Could be used for stereoscopic rendering perhaps. You can drive a pair of IR 3D glasses and sync it with the display. (I have some code for driving Sony protocol shutters and works great, it's not too hard).
- Another thing in the readme that would be convenient is a paragraph about the algorithm you made to optimize transfers. 
I read through the code and don't understand it quite yet. I'd expect a frame difference (prev frame - current frame) and blob detection. The blobs would then get uploaded. 
- A suggestion I have is to allow for **lossy uploading** with a setting. If a value changes by the least significant bit, it might not be a big deal to skip. The setting could have multiple levels for lossy uploading. In principle it be like `(prev frame - new frame) >> factor << factor`, or `/ factor * factor` .

And some questions:
- I am considering porting this to ESP32. It has a 40mhz ISP bus. I was thinking it would be a fun and cheap wired/wireless display driver. Any thoughts on that? The Wifi speed would be a limiting factor for driving it.

Cheers!

**Comment by juj** [comment]
Cleaning up resolved conversations.
