### ISSUE TITLE
fbcp-ili9341 does not initialize on boot

### ISSUE THREAD

**Issue by donutkeyboards** [juj/fbcp-ili9341#44]
Hello there,

I installed and compiled the driver for my Raspberry Pi Zero W running Retropie over Raspbian Stretch, and it seems that it won't start the driver after a reboot. The log says that it can't find the directory specified in rc.local (which I definitely copied and pasted there). Any advice? 

Thanks!

**Comment by donutkeyboards** [comment]
More specifically, it says "command not found" on boot

**Comment by donutkeyboards** [comment]
FIXED! I was simply not inputting the correct path. It might be worth mentioning in the documentation that the command is more like sudo /home/pi/fbcp-ili9341/build/fbcp-ili9341 & for the novices like myself.

**Comment by juj** [comment]
Thanks! This is a good suggestion, added an example in above commit to illustrate the actual line to add in the `/etc/rc.local` file.
