### ISSUE TITLE
Thoughts on Hyperpixel Screens?

### ISSUE THREAD

**Issue by jpete24** [juj/fbcp-ili9341#45]
Juj-
Was curious if you have experimented with either of the Hyperpixel displays, especially the new 4.0” version. I wonder if your driver could incorporate that display and the resolution that it puts out?

**Comment by juj** [comment]
The HyperPixel displays ([if this product?](https://shop.pimoroni.com/products/hyperpixel-4)) seem to use a DPI bus, which means that the Raspberry Pi GPU firmware has built-in support for outputting to the display. So a software driver such as fbcp-ili9341 is then not needed. (fbcp-ili9341 is only for SPI based displays)

The built-in firmware support should give it hiccup free 60fps update rate out of the box.

That aside, theoretically a resolution of 800x480 would not be infeasible for fbcp-ili9341 on an SPI display, but it naturally it would limit the maximum refresh rate, and increase CPU usage. On a Pi Zero, 800x480 would definitely be too much that one would have to resort to full screen updates, diffing 800x480 images would be too much work. On a Pi 3B, small graphical changes, such as X11 with only mouse cursor moving on screen, would still be expected to be fluid, although at a higher CPU overhead cost. I don't know if anyone actually manufactures a 800x480 sized SPI display, that is a bit high resolution for regular drivers to manage.
