### ISSUE TITLE
Driver Applies Overscan When Not Needed

### ISSUE THREAD

**Issue by Mootikins** [juj/fbcp-ili9341#5]
I'm working with FreePlay, we got pixel perfect to work, just thought you should know that you set the NES overscan settings to the default, so I'd comment them out on the repo version. We already made the change on our local copy.

**Comment by juj** [comment]
Thanks, I've been thinking to do some kind of runtime scaling mechanism to allow toggling between crop and scale. For testing I prefer to use the crop mode, but once I have time I'll look at migrating away from it as default.
