### ISSUE TITLE
Option -DILI9341=ON causes "not declared in this scope"

### ISSUE THREAD

**Issue by Riksu9000** [juj/fbcp-ili9341#6]
Building with settings for other displays works fine but running cmake with these settings causes multiple "not declared in this scope".
```
cmake -DPI_ZERO=ON -DILI9341=ON -DGPIO_TFT_DATA_CONTROL=24 -DGPIO_TFT_RESET_PIN=25 -DSPI_BUS_CLOCK_DIVISOR=6 ..
```
Output
[errors.txt](https://github.com/juj/fbcp-ili9341/files/2042468/errors.txt)

**Comment by juj** [comment]
Thanks for reporting, hopefully works now after above commit.
