### ISSUE TITLE
ILI9341 display white screen

### ISSUE THREAD

**Issue by tester962** [juj/fbcp-ili9341#61]
Hi! I have an ILI9341-based 2.8 inch LCD display that has no C/S pin.
I've connected it to my Pi3B and **it does work** using the fbtft driver, but no luck with fbcp-ili9341.

My build options:
`cmake -DILI9341=ON -DGPIO_TFT_DATA_CONTROL=24 -DGPIO_TFT_RESET_PIN=25 -DGPIO_TFT_BACKLIGHT=18 -DSPI_BUS_CLOCK_DIVISOR=18 -DBACKLIGHT_CONTROL=ON -DUSE_DMA_TRANSFERS=ON ..`

When I start the executable the LCD displays a white screen and nothing happens. 

I've tried disabling DMA transfers (the screen can't be turned off if I do that), increasing the bus clock divisor, changing the GPIO pins but I can't get it to work.

Output:

> pi@raspberrypi:~/fbcp-ili9341/build $ sudo ./fbcp-ili9341
> bcm_host_get_peripheral_address: 0x3f000000, bcm_host_get_peripheral_size: 16777216, bcm_host_get_sdram_address: 0xc0000000
> BCM core speed: current: 250000000hz, max turbo: 400000000hz. SPI CDIV: 18, SPI max frequency: 22222222hz
> Allocated DMA channel 7
> Allocated DMA channel 1
> Enabling DMA channels Tx:7 and Rx:1
> DMA hardware register file is at ptr: 0x75b09000, using DMA TX channel: 7 and DMA RX channel: 1
> DMA hardware TX channel register file is at ptr: 0x75b09700, DMA RX channel register file is at ptr: 0x75b09100
> Resetting DMA channels for use
> DMA all set up
> Initializing display
> Resetting display at reset GPIO pin 25
> Setting TFT backlight on at pin 18
> Creating SPI task thread
> InitSPI done
> Relevant source display area size with overscan cropped away: 720x480.
> Source GPU display is 720x480. Output SPI display is 320x240 with a drawable area of 320x240. Applying scaling factor horiz=0.44x & vert=0.44x, xOffset: 0, yOffset: 13, scaledWidth: 320, scaledHeight: 213
> Creating dispmanX resource of size 320x213 (aspect ratio=1.502347).
> GPU grab rectangle is offset x=0,y=0, size w=320xh=213, aspect ratio=1.502347
> All initialized, now running main loop...
>

**Comment by juj** [comment]
Everything does look good there, tough to say what would be wrong. If the display does not even blink black temporarily, then it means that it was not even able to initialize (fbcp-ili9341 clears the screen to black at start).

The only option I can think here is to use a logic analyzer to cross-reference working fbtft vs bad fbcp-ili9341 to figure out what might be different at boot.

Another thing to try may be to adjust the init sequence starting at

https://github.com/juj/fbcp-ili9341/blob/master/ili9341.cpp#L33

There are different ILI9341 init sequence PDF files floating around the web, perhaps different displays need some specific setup in there.

**Comment by petrkutalek** [comment]
Just for people searching for solution in the future – I had the same problem until I realized I forgot to remove `dtparam=spi=on` from `/boot/config.txt`.
