### ISSUE TITLE
Pi zero with adafruit 240x240 1.54" not working 

### ISSUE THREAD

**Issue by Diehard4077** [juj/fbcp-ili9341#69]
The driver I have is (st7789)

I have wired this up twice and I still can not get the screen to display even with multiple different  cmake changes 
![20190224_171528](https://user-images.githubusercontent.com/46288235/53306203-2cb75280-3858-11e9-95c9-f02428ba11ac.jpg)
![20190224_171518](https://user-images.githubusercontent.com/46288235/53306204-2cb75280-3858-11e9-9981-3c1d76f7c596.jpg)
![15510467870391527079307](https://user-images.githubusercontent.com/46288235/53306212-46f13080-3858-11e9-9531-56013227bbbc.jpg)

i started with sudo apt-get install cmake
git clone https://github.com/juj/fbcp-ili9341.git
cd fbcp-ili9341
mkdir build
cd build
cmake -DST7789=ON -DGPIO_TFT_DATA_CONTROL=18 -DGPIO_TFT_RESET_PIN=23 -DSPI_BUS_CLOCK_DIVISOR=6  ..
make -j
sudo ./fbcp-ili9341

- everything seemed ok but the screen stays black so  i deleted the build and tried sudo apt-get install cmake
git clone https://github.com/juj/fbcp-ili9341.git
cd fbcp-ili9341
mkdir build
cd build
cmake -DST7789=ON -DGPIO_TFT_DATA_CONTROL=18 -DGPIO_TFT_RESET_PIN=23 -DSPI_BUS_CLOCK_DIVISOR=10 -DSINGLE_CORE_BOARD=ON ..
make -j
sudo ./fbcp-ili9341

-still a black screen so deleted the build and tried
 
sudo apt-get install cmake
git clone https://github.com/juj/fbcp-ili9341.git
cd fbcp-ili9341
mkdir build
cd build
cmake -DST7789=ON -DDMA_TX_CHANNEL=3 -DDISPLAY_BREAK_ASPECT_RATIO_WHEN_SCALING=ON -DUSE_DMA_TRANSFERS=ON -DGPIO_TFT_DATA_CONTROL=18 -DGPIO_TFT_RESET_PIN=23 -DSPI_BUS_CLOCK_DIVISOR=30 -DSINGLE_CORE_BOARD=ON ..
make -j
sudo ./fbcp-ili9341

still im getting a black screen im really stuck and would love any help i could get

**Comment by nhenry1647** [comment]
Try ST7789VW.  I have this running on a 240x240 screen as well and it does
work.  Also try deleting the build folder to start a fresh compile.

**Comment by Diehard4077** [comment]
I was deleting the build file each time as well as restarting and removing the power from the pi I guess I could try the VW variant

**Comment by Crackedconsole** [comment]
I am working with a raspberrypi zero w as well trying to get a similar 1.54inch LCD to work with this driver.
I've tried both ST7789 and ST7789VW
https://www.aliexpress.com/item/Raspberry-Pi-Game-zero-W-2B-3B-1-54inch-mini-LCD-touchscreen/32970035492.html?spm=a2g0s.12269583.0.0.159b43fcoQ6btZ

I reached out to the manufacture and they verified the display driver IC is a ST7789 and provided a spec sheet. It showed datachannel as BCM pin 22 and RST as 27.

I've tried several fresh makes using both ST7789 and ST7789VW, with DMA transfers on and off, between 60-4 clock divisor, 2 different DMA channel settings all to no avail and just a blank screen.

THOUGH, oddly, when I set the DC pin to 27 during the make process and use the ST7789VW option, for just 1-2 frames I get a flash of the console boot when the driver is initialized.

Has anyone had success with this driver on these 1.54inch screens and a PiZero, or even specifically the device I'm working with?

Thank you

**Comment by Crackedconsole** [comment]
I found this below works for my display (1.54 inch with ST7789 driver), yet last night I had the -DTS7789VW=on at the end of the string and it never worked oddly. Moving it to the front and it now works. Though I did also add explicitly "DUSE_DMA_TRANSFERS=ON"

 cmake -DST7789VW=ON -DGPIO_TFT_DATA_CONTROL=22 -DGPIO_TFT_RESET_PIN=27 -DUSE_DMA_TRANSFERS=ON -DSPI_BUS_CLOCK_DIVISOR=4 -DDISPLAY_ROTATE_180_DEGREES=ON -DSTATISTICS=0 ..

**Comment by winterism** [comment]
> I found this below works for my display (1.54 inch with ST7789 driver), yet last night I had the -DTS7789VW=on at the end of the string and it never worked oddly. Moving it to the front and it now works. Though I did also add explicitly "DUSE_DMA_TRANSFERS=ON"
> 
> cmake -DST7789VW=ON -DGPIO_TFT_DATA_CONTROL=22 -DGPIO_TFT_RESET_PIN=27 -DUSE_DMA_TRANSFERS=ON -DSPI_BUS_CLOCK_DIVISOR=4 -DDISPLAY_ROTATE_180_DEGREES=ON -DSTATISTICS=0 ..

Thanks for sharing your config. 
I have more question. What is your rasbian img? Is it official or custom?

**Comment by juj** [comment]
Closing old issues.
