### ISSUE TITLE
Tested support for Pi 1B rev 2, 2B, 3B with waveshare 1.3" lcd 

### ISSUE THREAD

**Issue by tlrasor** [juj/fbcp-ili9341#72]
I have tested support for the`WaveShare 128x128, 1.44inch LCD display HAT for Raspberry Pi with ST7735S controller` across all three Pi generations, 1B rev 2, 2B, and 3B. All the models worked perfectly fine out of the box but with some caveats: was only able to get the clock divisor down to 20 before getting weird stuff happening. 20 still gave decent enough performance for the likely use cases of this super budget display (pi hole statistics n stuff). I highly advise overclocking the 1B to 'turbo', I got better performance without any real impact to temps. The 2B and 3B performed fine without overclocking.

**Comment by juj** [comment]
Thanks for data points, info like this is much appreciated!

Given that you were able to test across all the Pis, something that I have been wondering is if different Pi versions have different max bandwidth performance characteristics, or if they all are able to achieve same data rate when used with the same display. On an ILI9341 display I have not seen differences, but had a practical scenario to test extensively.
