### ISSUE TITLE
strange numbers in top left corner for waveshare 1.44in lcd 

### ISSUE THREAD

**Issue by krzysztofkuczek** [juj/fbcp-ili9341#77]
Hi,
Everything works fine, driver compiled for pi zero board with following flags
`cmake -DWAVESHARE_ST7735S_HAT=ON -DSPI_BUS_CLOCK_DIVISOR=12 ..`
The only issue is that strange numbers/letters (maybe debug info?) id displayed in top left corner.

![IMG_20190313_210030](https://user-images.githubusercontent.com/1246883/54311078-248b4100-45d4-11e9-86f2-ddad009586f0.jpg)

Thank you in advance
Kris

**Comment by krzysztofkuczek** [comment]
solved by adding -DSTATISTICS=0 :)
Maybe it should be default...

**Comment by Merith-TK** [comment]
Did you ever fix the issue where the display signal is larger than the actual physical display, so fbcp scales it to the screen leaving you with a squished, unusable screen?

**Comment by juj** [comment]
You can adjust the video resolution in hdmi_mode directive in /boot/config.txt. If you make it match the native resolution of the display, then there will be no scaling.
